config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'

  get '/inquiries/new', to: 'inquiries#new', as: 'new_inquiry'
  post '/inquiries', to: 'inquiries#create'

  get '/case', to: 'pages#case_study', as: 'case_study'
  get '/our_team', to: 'pages#our_team', as: 'our_team'
  resources :application
  resources :pages
  resources :inquiries

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
# == Schema Information
#
# Table name: inquiries
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string
#  message    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Inquiry < ApplicationRecord

  attr_accessor :name, :email, :content

  validates :name,
    presence: true

  validates :email,
    presence: true

  validates :message,
    presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController

  def new
    @inquiry = Inquiry.new
  end

def create
  @inquiry = Inquiry.new(allowed_params)
  if @inquiry.valid?
    InquiryMailer.new_inquiry(@inquiry).deliver
    redirect_to root_path, notice: "Your messages has been sent."
  else
    flash.now[:error] = 'Cannot send message.'
    render :new
  end
end

private

def allowed_params
  params.require(:inquiry).permit(:name, :email, :message)
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @inquiry = Inquiry.new
  end



  def case_study
  end

  def our_team
    
  end

  def contact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/inquiries/_new.html.erb
<div class="form-container" id="contact-modal">
  <a href="#" class="modal-close" id="close-modal">Close</a>
  <hgroup class="form-header flex-center">
    <h3>Ready, set, code! Send us a note below, or call
<span>+1 (812) 322-7392</span> to speak with us about your project.
We look forward to hearing from you.</h3>
  </hgroup>
  <div class="flex-center">
    <div class="small-12 large-10 column">
      <!-- validation error -->
      <div class="alert row small-6 column">
        <%= flash[:error] %>
      </div>

      <%= form_for @inquiry do |f| %>
      <fieldset>
        <div class="row small-10 large-8 column">
          <%= f.text_field :name, placeholder: "Name" %>
        </div>
          
        <div class="row small-10 large-8 column">
          <%= f.email_field :email, placeholder: "Email address"%>
        </div>

        <div class="row small-10 large-8 column">
          <%= f.text_area :message, placeholder: "Project description"%>
        </div>
      </fieldset>
          <br />
      <fieldset>
        <div class="row small-10 large-8 column">
          <%= f.submit "Send", class: "button expand" %>
        </div>
      </fieldset>
    <% end %>
    </div>
  </div>
</div>

app/views/inquiries/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <p class="form-back"><%= link_to 'Back', root_path %><p>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/inquiries/new.js.erb
$("body").append("<%= j render 'new' %>");
$("#close-modal").click(function(e){
  $("#contact-modal").remove();
  e.preventDefault();
})

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Sid3car" %></title>

    <%= stylesheet_link_tag    "application" %>

    <link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">
    <%= csrf_meta_tags %>
  </head>
  <div class="mobile-menu hide" id="mobileMenu">
    <div><%= link_to "", root_path, class: "sid3car-logo-mobile" %></div>
    <aside class="exit" id="exit"><span>X<span></aside>
    <ul>
      <li><%= link_to 'About us', our_team_path, class: 'inverse' %></li>
      <li><%= link_to 'Portfolio', case_study_path, class: 'inverse' %></li>
      <li><%= link_to 'Cowork', '#', class: 'inverse' %></li>
      <li><%= link_to 'Decal', '#', class: 'inverse' %></li>
      <li data-reveal-id="myModal"><%= link_to 'Contact', new_inquiry_path, class: 'inverse', remote: true %></li>
    </ul>
  </div>


    <%= yield %>

  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/pages/case_study.html.erb
<header class="masthead-background HQE-background">
  <div><%= link_to "", root_path, class: "sid3car-logo" %></div>
  <nav class="top-bar HQE-background" >
    <div class="top-bar-right">
      <ul class="menu top-menu hide" id="desktopMenu">
        <li><%= link_to 'About us', our_team_path, class: 'inverse' %></li>
        <li><%= link_to 'Portfolio', '#', class: 'inverse' %></li>
        <li><%= link_to 'Cowork', '#', class: 'inverse' %></li>
        <li><%= link_to 'Decal', '#', class: 'inverse' %></li>
        <li><%= link_to 'Contact', new_inquiry_path, class: 'inverse', remote: true %></li>
      </ul>
    </div>
    <div class='menu-icon' id='hamburger'>Menu</div>
  </nav>
  <div class="clearfix"></div>
  <section class="intro">
    <hgroup>
      <h1>Hoosiers for Quality Education</h1>
      <div><a href="#" class="white-link">Visit website<span>&#866</span></a></div>
    </hgroup>
    <p>XOXO tilde irony Kickstarter, McSweeney's Intelligentsia keytar
      distillery. Direct trade farm-to-table asymmetrical synth mixtape.
      Photo booth sartorial bitters Austin banh mi. Kickstarter try-hard
      ethical Odd Future Intelligentsia wayfarers cardigan 90's lumbersexual.
      8-bit Truffaut Schlitz tilde, kogi bitters skateboard fixie tofu
      farm-to-table food truck deep v lumbersexual. Readymade brunch scenester
      cred flannel. Single-origin coffee slow-carb migas, Williamsburg
      biodiesel direct trade freegan. </p>

  </section>
</header>
<section class="case_content">
  <p>Freegan distillery 90's, art party church-key High Life Wes Anderson
    beard YOLO Tumblr ennui. Typewriter cred sustainable letterpress.
    Actually plaid Carles, quinoa pop-up yr listicle keytar 90's Portland
    street art narwhal. Cray Echo Park Neutra meggings Carles sriracha
    artisan, meditation ugh Williamsburg. Before they sold out Tumblr
    freegan, narwhal McSweeney's sriracha squid viral selvage brunch
    bespoke four loko 3 wolf moon. Lomo semiotics kogi, single-origin
    coffee Thundercats messenger bag gentrify XOXO chambray cardigan shabby
    chic mustache quinoa keffiyeh synth. Swag bitters Neutra photo booth vegan.
    Twee Truffaut listicle Neutra. VHS quinoa twee ethical listicle Odd
    Future, occupy flexitarian wolf mustache.</p>
</section>
<section class="case_display">
  <%= image_tag 'case_graph.png', alt: 'graph' %>
</section>
<section class="case_content">
  <p>Forage organic letterpress Pinterest. Kogi organic Schlitz before they
    sold out, biodiesel American Apparel dreamcatcher gentrify Thundercats.
    Mumblecore 3 wolf moon seitan Helvetica, squid freegan swag skateboard
    heirloom. Tilde synth food truck, ethical Blue Bottle crucifix small batch
    meggings dreamcatcher brunch seitan. Lo-fi narwhal Truffaut kogi, artisan
    irony pork belly pickled XOXO dreamcatcher twee polaroid Odd Future art
    party. Freegan distillery 90's, art party church-key High Life Wes Anderson
    beard YOLO Tumblr ennui. Typewriter cred sustainable letterpress.</p>
  <p>Actually plaid Carles, quinoa pop-up yr listicle keytar 90's Portland
    street art narwhal. Cray Echo Park Neutra meggings Carles sriracha
    artisan, meditation ugh Williamsburg. Before they sold out Tumblr freegan,
    narwhal McSweeney's sriracha squid viral selvage brunch bespoke four loko
    3 wolf moon. Lomo semiotics kogi, single-origin coffee Thundercats
    messenger bag gentrify XOXO chambray cardigan shabby chic mustache quinoa
    keffiyeh synth. Swag bitters Neutra photo booth vegan. Twee Truffaut
    listicle Neutra. VHS quinoa twee ethical listicle Odd Future, occupy
    flexitarian wolf mustache.</p>
</section>
<section class="metrics-container">
  <div>
    <h4>Before 2013</h4>
    <ul>
      <li>0 Actions</li>
      <li>8 Emails</li>
      <li>29 Tweets</li>
    </ul>
  </div>
  <div>
    <h4>After 2013</h4>
    <ul>
      <li>1,024 Actions</li>
      <li>850 Emails</li>
      <li>629 Tweets</li>
    </ul>
  </div>
</section>
<section class="start flex-center">
  <p><a href="#" class="button">Start your project</a></p>
</section>
<footer>
  <ul class="menu small-12 large-6 columns">
    <li><%= link_to 'Our Team', our_team_path %></li>
    <li><%= link_to 'Portfolio', case_study_path %></li>
    <li><%= link_to 'Cowork', '#' %></li>
    <li><%= link_to 'Contact', new_inquiry_path, remote: true %></li>
  </ul>
  <p class="align-right small-12 large-6 columns">
    Made with <span class="em em-heart"></span> in <a href="#" class="to-link">Bloomington, IN</a>
  </p>
</footer>

app/views/pages/index.html.erb
<header class="masthead-background">
  <div><%= link_to "", root_path, class: "sid3car-logo" %></div>
  <nav class="top-bar">
    <div class="top-bar-right">
      <ul class="menu top-menu hide" id="desktopMenu">
        <li><%= link_to 'About us', our_team_path, class: 'inverse' %></li>
        <li><%= link_to 'Portfolio', case_study_path, class: 'inverse' %></li>
        <li><%= link_to 'Cowork', '#', class: 'inverse' %></li>
        <li><%= link_to 'Decal', '#', class: 'inverse' %></li>
        <li><%= link_to 'Contact', new_inquiry_path, class: 'inverse', remote: true %></li>
      </ul>
    </div>
    <div class='menu-icon' id='hamburger'>Menu</div>

  </nav>
  <div class="statement">
    <p>We make <span class="transparent-statement">custom software</span> for subject matter experts.<span class="emoji">&#128083</span></p>
  </div>
  <div class="cta">
    <ul class="dropdown menu flex-left top-menu" data-dropdown-menu >
      <li class="border-white">
        <a href="#" class="inverse">my business</a>
        <ul class="menu vertical top-menu">
          <li><a href='#' class="inverse"></a></li>
          <li><a href='#' class="inverse"></a></li>
          <li><a href='#' class="inverse"></a></li>
        </ul>
      </li>
      <li class="border-white">
        <a href="#" class="inverse">needs a new</a>
        <ul class="menu vertical top-menu">
          <li><a href='#' class="inverse">needs to update its</a></li>
          <li><a href='#' class="inverse">needs advice on</a></li>
          <li><a href='#' class="inverse"></a></li>
        </ul>
      </li>
      <li class="border-white">
        <a href="#" class="inverse">web application</a>
        <ul class="menu vertical top-menu">
          <li><a href='#' class="inverse">website</a></li>
          <li><a href='#' class="inverse">ecommerce application</a></li>
          <li><a href='#' class="inverse"></a></li>
        </ul>
      </li>
      <li>
        <a href="#" class="button orange">Get started</a>
      </li>
    </ul>
  </div>
</header>
<section class="flex-center msg">
  <p>Since 2012, we've helped startups, non-profits, and small businesses solve
  problems (or enhance current solutions) with technology.</p>
</section>
<section class="fuel">
  <article>
    <h2>Fuel for your fire.<span class="emoji">&#128293</span></h2>
    <p>We’re a small team of designers, developers and product strategists
      passionate about building and scaling organization-altering software.
      Just this year, our products have helped clients attract nearly 200,000
      unique visitors and over $1 million dollars in new revenue.</p>
    <p><a href="#" class="to-link">View case study <span>&#866</span></a></p>
  </article>
</section>
<section class="work-preview">
  <article class="row">
    <div class="small-12 large-4 columns">
      <ul>
        <li class="feature-work">
          <h3>Institute for Quality Education</h3>
          <h6>EDUCATION</h6>

          <p>Use the Hoosiers for Quality Education’s political Action Center
            to research regional policies and motivate local legislators. </p>
          <a href='#' class="button">View case study</a>
        </li>
        <li>
          <h3>Adproval</h3>
          <h6>NON-PROFIT</h6>

          <p>helped Adproval bring its new and improved internet advertising
            software to market quickly and without hickup.</p>
        </li>
        <li>
          <h3>The Venture Game</h3>
          <h6>NON-PROFIT</h6>

          <p>Sid3car built software to help educators at the Kelley School of
            Business administor a six week venture stimulation. </p>
        </li>
        <li class="feature-work">
          <h3>Plus Time</h3>
          <h6>EDUCATION</h6>

          <p>Flex scheduling software for middle and high school enrichment
             programs. </p>
          <a href='#' class="button">View case study</a>
        </li>
        <li>
          <h3>Mensani</h3>
          <h6>ATHLETIC TRAINING</h6>

          <p>Use the Hoosiers for Quality Education’s political Action
            Center to research regional policies and motivate local
            legislators. </p>
        </li>
      </ul>
    </div>
    <div class="small-12 large-4 columns">
      <ul>
        <li>
          <h3>Hoosiers for Quality Education</h3>
          <h6>EDUCATION</h6>

          <p>Use the Hoosiers for Quality Education’s political Action
            Center to research regional policies and motivate local
            legislators. </p>
        </li>
        <li>
          <h3>Hydrating Humanity</h3>
          <h6>NON-PROFIT</h6>

          <p>A custom crowdraising platform for the Carolinas’ leading
            clean water non-profit increased donations by 40%.  </p>
        </li>
        <li class="feature-work">
          <h3>StoreOptics</h3>
          <h6>FOOD SERVICE</h6>

          <p>Mobile field service management for retail stores and
            their vendors.  </p>
          <a href='#' class="button">View case study</a>
        </li>
        <li>
          <h3>RideAmigos</h3>
          <h6>NON-PROFIT</h6>

          <p>Provisional development help allowed RideAmigos to ship their
            Multi-Modal Trip Planner on time and on budget. </p>
        </li>
        <li>
          <h3>Hoosiers for Quality Education</h3>
          <h6>EDUCATION</h6>

          <p>Use the Hoosiers for Quality Education’s political Action Center
             to research regional policies and motivate local legislators. </p>
        </li>
      </ul>
    </div>
    <div class="small-12 large-4 columns">
      <ul>
        <li class="feature-work">
          <h3>LaunchPad</h3>
          <h6>REAL ESTATE</h6>

          <p>Apartment management software for forward-thinking landlords. </p>
          <a href='#' class="button">View case study</a>
        </li>
        <li>
          <h3>The Switchboard</h3>
          <h6>EDUCATION</h6>

          <p>The Switchboard helps stimulate the regional economy by helping
            Bloomington entreprenuers find and connect with local
            service providers. </p>
        </li>
        <li class="feature-work">
          <h3>Sound Mind Investments</h3>
          <h6>FINANCIAL SERVICES</h6>

          <p>Track direct share balances, forcast portfolio growth,
            and plan for retirement with Sound Mind Investment’s
            Stewardship Planner. </p>
          <a href='#' class="button">View case study</a>
        </li>
        <li>
          <h3>39&deg North</h3>
          <h6>NON-PROFIT</h6>

          <p>Provisional development help allowed RideAmigos to ship their
            Multi-Modal Trip Planner on time and on budget. </p>
        </li>
        <li>
          <h3>State Innovation Exchange</h3>
          <h6>NON-PROFIT</h6>

          <p>Provisional development help allowed RideAmigos to ship
            their Multi-Modal Trip Planner on time and on budget. </p>
        </li>
      </ul>
    </div>
  </article>
</section>
<section class="lean">
  <div>
    <h2>Unaplogetically Lean</h2>
    <p>We’re proud to offer world-class service from an affordable
      city and our very own <a href="#" class="to-link">coworking space</a>.
      Low overhead means eliminating typical agency inefficiencies
      to complete your project quickly and less expensively. </p>
    <p><a href="#" class="to-link meet-link">Meet Sid3car<span>&#866</span></a></p>
  </div>
</section>
<section class="testimonial">
  <div>
      <p class="quote-container"><span class="quote">"</span>Sid3car delivered San Fransisco-style software without any of the
      traditional agency headache. We’ll be back!</p>
      <br />
    <p>Mathew Anderson | Adproval</p>
  </div>
</section>
<section class="start flex-center">
  <p><a href="#" class="button">Start your project</a></p>
</section>
<footer>
  <ul class="menu small-12 large-6 columns">
    <li><%= link_to 'Our Team', our_team_path %></li>
    <li><%= link_to 'Portfolio', case_study_path %></li>
    <li><%= link_to 'Cowork', '#' %></li>
    <li><%= link_to 'Contact', new_inquiry_path, remote: true %></li>
  </ul>
  <p class="align-right small-12 large-6 columns">
    Made with <span class="em em-heart"></span> in <a href="#" class="to-link">Bloomington, IN</a>
  </p>
</footer>

app/views/pages/our_team.html.erb
<header class="masthead-background">
  <div><%= link_to "", root_path, class: "sid3car-logo" %></div>
  <nav class="top-bar" >
    <div class="top-bar-right">
      <ul class="menu top-menu hide" id="desktopMenu">
        <li><%= link_to 'About us', our_team_path, class: 'inverse' %></li>
        <li><%= link_to 'Portfolio', case_study_path, class: 'inverse' %></li>
        <li><%= link_to 'Cowork', '#', class: 'inverse' %></li>
        <li><%= link_to 'Decal', '#', class: 'inverse' %></li>
        <li><%= link_to 'Contact', new_inquiry_path, class: 'inverse', remote: true %></li>
      </ul>
    </div>
    <div class='menu-icon' id='hamburger'>Menu</div>
  </nav>


    <hgroup>
      <div class="statement">
        <h1>Honest. <span class="transparent-statement">Trustworthy.</span> Cool People.</h1>
        <div>How can we help?</div>
      </div>

    </hgroup>
  <section class="intro">
    <p>XOXO tilde irony Kickstarter, McSweeney's Intelligentsia keytar
      distillery. Direct trade farm-to-table asymmetrical synth mixtape.
      Photo booth sartorial bitters Austin banh mi. Kickstarter try-hard
      ethical Odd Future Intelligentsia wayfarers cardigan 90's lumbersexual. </p>
  </section>
</header>
<section class="team-container">

  <div class="image-container flex-center large-10">
    <h2 class="flex-center"> The Team </h2>
    <aside id="bio-exit">X</aside>
    <div class="profile-pic flex-left" id="forrest">
      <%= image_tag 'Forrest.png' %>
      <div class="hover-preview">
        <ul>
          <li><h6>Forrest Fowler</h6></li>
          <li>Founder</li>
          <li>Heavyweight, full-stack developer</li>
        </ul>
      </div>
      <article class="bio-container">

        <hgroup class="center">
          <h1>Forrest Fowler</h1>
          <h5>Founder</h5>
        </hgroup>
        <p>XOXO tilde irony Kickstarter, McSweeney's Intelligentsia keytar
          distillery. Direct trade farm-to-table asymmetrical synth mixtape.
          Photo booth sartorial bitters Austin banh mi. Kickstarter try-hard
          ethical Odd Future Intelligentsia wayfarers cardigan 90's
          lumbersexual.</p>
          <section>
            <h3 class="center">Projects</h3>
            <ul class="flex-center">
              <li></li>
            </ul>
          </section>
          <div class="center"><%= link_to 'View more of Forrest\'s work', '#' %> </div>
      </article>
    </div>
    <div class="profile-pic flex-left" id="Tyler">
      <%= image_tag 'Tyler.png' %>
      <div class="hover-preview">
        <ul>
          <li><h6>Tyler Henke</h6></li>
          <li>Founder</li>
          <li>Graphic Desiger</li>
        </ul>
      </div>
      <article class="bio-container">
        <hgroup class="center">
          <h1>Tyler Henke</h1>
          <h5>Founder</h5>
        </hgroup>
        <p>XOXO tilde irony Kickstarter, McSweeney's Intelligentsia keytar
          distillery. Direct trade farm-to-table asymmetrical synth mixtape.
          Photo booth sartorial bitters Austin banh mi. Kickstarter try-hard
          ethical Odd Future Intelligentsia wayfarers cardigan 90's
          lumbersexual.</p>
          <section>
            <h3 class="center">Projects</h3>
            <ul class="flex-center">
              <li></li>
            </ul>
          </section>
          <div class="center"><%= link_to 'View more of Tyler\'s work', '#' %> </div>
      </article>
    </div>
    <div class="profile-pic flex-left" id="other-person">
      <%= image_tag 'Forrest.png' %>
      <div class="hover-preview">
        <ul>
          <li><h6>Forrest Fowler</h6></li>
          <li>Founder</li>
          <li>Heavyweight, full-stack developer</li>
        </ul>
      </div>
      <article class="bio-container">
        <hgroup class="center">
          <h1>Forrest Fowler</h1>
          <h5>Founder</h5>
        </hgroup>
        <p>XOXO tilde irony Kickstarter, McSweeney's Intelligentsia keytar
          distillery. Direct trade farm-to-table asymmetrical synth mixtape.
          Photo booth sartorial bitters Austin banh mi. Kickstarter try-hard
          ethical Odd Future Intelligentsia wayfarers cardigan 90's
          lumbersexual.</p>
          <section>
            <h3 class="center">Projects</h3>
            <ul class="flex-center">
              <li></li>
            </ul>
          </section>
          <div class="center"><%= link_to 'View more of Forrest\'s work', '#' %> </div>
      </article>
    </div>
  </div>
</section>
<footer>
  <ul class="menu small-12 large-6 columns">
    <li><%= link_to 'Our Team', our_team_path %></li>
    <li><%= link_to 'Portfolio', case_study_path %></li>
    <li><%= link_to 'Cowork', '#' %></li>
    <li><%= link_to 'Contact', new_inquiry_path, remote: true %></li>
  </ul>
  <p class="align-right small-12 large-6 columns">
    Made with <span class="em em-heart"></span> in <a href="#" class="to-link">Bloomington, IN</a>
  </p>
</footer>